# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('movement_type', models.CharField(choices=[('in', 'Kirdi'), ('out', 'Chiqdi'), ('return_in', 'Qaytib keldi'), ('return_out', 'Qaytarildi'), ('adjust', 'Tuzatish')], db_index=True, max_length=15, verbose_name='harakat turi')),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Har doim musbat son — yo'nalish movement_type dan aniqlanadi", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='miqdor')),
                ('qty_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='harakatdan oldin')),
                ('qty_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='harakatdan keyin')),
                ('source_type', models.CharField(blank=True, help_text='purchase | sale | manual', max_length=50, verbose_name='manba turi')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='manba ID')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='sabab / izoh')),
            ],
            options={
                'verbose_name': 'ombor harakati',
                'verbose_name_plural': 'ombor harakatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='miqdor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'qoldiq',
                'verbose_name_plural': 'qoldiqlar',
                'ordering': ['product__name'],
            },
        ),
    ]
