# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='miqdor')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Ushbu xarid narxi', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tan narxi')),
                ('sell_price', models.DecimalField(decimal_places=2, help_text='Xarid paytida belgilangan sotish narxi', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sotish narxi')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jami')),
            ],
            options={
                'verbose_name': 'xarid qatori',
                'verbose_name_plural': 'xarid qatorlari',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="to'lov summasi")),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
            ],
            options={
                'verbose_name': "to'lov",
                'verbose_name_plural': "to'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_no', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='hisob-faktura raqami')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('received', 'Qabul qilindi'), ('partial', "Qisman to'landi"), ('paid', "To'liq to'landi"), ('cancelled', 'Bekor qilindi')], db_index=True, default='draft', max_length=20, verbose_name='holat')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jami summa')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="to'langan summa")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='qarz')),
                ('due_date', models.DateField(blank=True, help_text='15, 30 kun yoki istalgan sana', null=True, verbose_name="to'lov muddati")),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='qabul qilingan vaqt')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='companies.branch', verbose_name='filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='companies.company', verbose_name='kompaniya')),
            ],
            options={
                'verbose_name': 'xarid',
                'verbose_name_plural': 'xaridlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
