# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.utils.timezone
import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=150, verbose_name="to'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='rasm')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('cashier', 'Kassir'), ('storekeeper', 'Omborchi'), ('accountant', 'Buxgalter')], db_index=True, default='cashier', max_length=20, verbose_name='rol')),
                ('language', models.CharField(choices=[('uz', "O'zbek (lotin)"), ('uz_cryl', 'Ўзбек (кирилл)'), ('ru', 'Русский')], default='uz', max_length=10, verbose_name='til')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='xodim')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="qo'shilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'foydalanuvchi',
                'verbose_name_plural': 'foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
