# Generated by Django 5.2.1 on 2026-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('restore', 'Qaytarildi'), ('purchase_received', 'Xarid qabul qilindi'), ('purchase_paid', "Xarid to'lovi amalga oshdi"), ('purchase_cancelled', 'Xarid bekor qilindi'), ('sale_checkout', 'Sotuv yakunlandi'), ('sale_return', 'Sotuv qaytarildi'), ('stock_adjust', 'Ombor tuzatildi')], db_index=True, max_length=30, verbose_name='harakat')),
                ('model_name', models.CharField(db_index=True, help_text='User, Product, Sale, Purchase ...', max_length=50, verbose_name='model')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='obyekt ID')),
                ('object_repr', models.CharField(help_text="Masalan: 'Lipton choy 100g' yoki 'Ali Karimov'", max_length=255, verbose_name='obyekt nomi')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": ["eski qiymat", "yangi qiymat"]}', verbose_name="o'zgarishlar")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('extra', models.JSONField(blank=True, default=dict, help_text="Har qanday qo'shimcha context (invoice_no, amount...)", verbose_name="qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'audit yozuvi',
                'verbose_name_plural': 'audit yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
