# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nomi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('address', models.TextField(blank=True, verbose_name='manzil')),
                ('inn', models.CharField(blank=True, help_text='Soliq raqami', max_length=20, verbose_name='INN')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'kompaniya',
                'verbose_name_plural': 'kompaniyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('address', models.TextField(blank=True, verbose_name='manzil')),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='kompaniya')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiallar',
                'ordering': ['company__name', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'name'), name='unique_branch_name_per_company')],
            },
        ),
    ]
