# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nomi')),
                ('short_name', models.CharField(help_text='Masalan: dona → d, kilogram → kg', max_length=10, verbose_name='qisqa nomi')),
            ],
            options={
                'verbose_name': "o'lchov birligi",
                'verbose_name_plural': "o'lchov birliklari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon nomi. Masalan: 🥛', max_length=50, verbose_name='ikonka')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='ota kategoriya')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nomi')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN-13, EAN-8, QR code...', max_length=100, null=True, unique=True, verbose_name='barcode / QR')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Oxirgi xarid narxi', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tan narxi')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sotish narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='rasm')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Bu miqdordan pastga tushsa ogohlantirish yuboriladi', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum qoldiq')),
                ('is_active', models.BooleanField(default=True, help_text="Faol bo'lmagan mahsulot sotilmaydi", verbose_name='faol')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='kategoriya')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit', verbose_name="o'lchov birligi")),
            ],
            options={
                'verbose_name': 'mahsulot',
                'verbose_name_plural': 'mahsulotlar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'), models.Index(fields=['is_active', 'deleted_at'], name='products_pr_is_acti_68bc6a_idx')],
            },
        ),
    ]
