# Generated by Django 5.2.1 on 2026-05-19 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_no', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='chek raqami')),
                ('status', models.CharField(choices=[('completed', 'Yakunlandi'), ('returned', 'Qaytarildi'), ('partial', 'Qisman qaytarildi')], db_index=True, default='completed', max_length=20, verbose_name='holat')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jami summa')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='chegirma %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='chegirma summasi')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="to'lanadigan summa")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="to'langan summa")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="nasiya qoldig'i")),
                ('note', models.TextField(blank=True, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'sotuv',
                'verbose_name_plural': 'sotuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='miqdor')),
                ('sell_price', models.DecimalField(decimal_places=2, help_text='Sotuv paytidagi narx (snapshot)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sotish narxi')),
                ('cost_price_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Foyda hisoblash uchun saqlanadi', max_digits=14, verbose_name='tan narxi (snapshot)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='jami')),
            ],
            options={
                'verbose_name': 'sotuv qatori',
                'verbose_name_plural': 'sotuv qatorlari',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], max_length=10, verbose_name="to'lov usuli")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='summa')),
            ],
            options={
                'verbose_name': "sotuv to'lovi",
                'verbose_name_plural': "sotuv to'lovlari",
            },
        ),
    ]
